### ISSUE TITLE
Встречи с заказчиком

### ISSUE THREAD

**Issue by inctnce** [inctnce/timetable-generator#2]
**Здесь будут появляться краткие итоги встреч с заказчиком**

**Comment by inctnce** [comment]
**25-09-2020**
Приложение должно показывать таблицу, которую можно загрузить/распечатать. 
Строка - время, столбец - кабинет(занят/не занят) или преподаватель(в какое время в каком кабинете) и т .д

Пишем без сервера на основе апи timetable.
Полная документация к API подъедет чуть позже, а пока что вот: [ссыло4ка](https://drive.google.com/file/d/1m88JP6af_udiCM6kNkHuN_9ozJXj3fdy/view?usp=sharing)

**Comment by runnia** [comment]
**06-10-2020**
Обсудили дизайн, возникли некоторые вопросы, связанные с функционалом и внешним видом:

Что важнее в расписании по кабинетам? Группа/преподаватель/предмет? (Предмет)

Хорошо бы добавить возможность хранить куки(или что-то подобное) для выбранного ранее адреса

Возможность сначала выбрать адрес, потом по нему показать все кабинеты на этом адресе (Так удобнее для работников)

Стоит показывать пустой день каким-нибудь сереньким, нужно продумать этот момент

Нужно подписывать год к месяцу, указанному сверху страницы, так как при просмотре расписания по преподавателю можно дойти до предыдущего года и перепутать

Хорошо бы добавить возможность посмотреть все свободные кабинеты прямо сейчас на конкретном адресе

Рассмотреть возможность отображения нескольких предметов в одном кабинете (такого не должно быть, но это встречается в нашем расписании и нужно это учесть), нужно например подчеркнуть красным, чтобы диспетчер сразу это увидела

**Comment by inctnce** [comment]
**25-10-2020**
"Список" с расписанием кабинетов, как и "таблицу", реализуем по типу  гугл календаря.  
Перевод на английский не требуется, поэтому свитчер не нужен (его итак сейчас нет).  
Поиск реализуется просто по содержанию подстроки в строке. Важно, чтобы результаты отображались динамически.  
Организационную деятельность лучше перенести в issues. 
Перевести кнопку с датами на русский. 
Попытаться найти баг с неверной сортировкой кабинетов. 
Исправить баг с обнулением (его нет) кабинетов при возврате назад к странице выбора адреса
