### ISSUE TITLE
Сравнение для сортировки

### ISSUE THREAD

**Issue by spogozhev** [inctnce/timetable-generator#34]
https://github.com/inctnce/timetable-generator/blob/2bddf442e2433db153fa1974efdf5f8bccc2509d/src/helpers/sortTimetableDays/sortIntervals.ts#L21

Возможно, следует в случае равных элементов возвращать 0.
if (hour_a === hour_b)
return  minute_a < minute_b ? -1 : (minute_b < minute_a ? 1 : 0);

**Comment by inctnce** [comment]
> https://github.com/inctnce/timetable-generator/blob/2bddf442e2433db153fa1974efdf5f8bccc2509d/src/helpers/sortTimetableDays/sortIntervals.ts#L21
> 
> Возможно, следует в случае равных элементов возвращать 0.
> if (hour_a === hour_b)
> return minute_a < minute_b ? -1 : (minute_b < minute_a ? 1 : 0);

У нас вроде не должно быть равных элементов, потому что мы добавляем временные интервалы в Set (он по умолчанию хранит в себе уникальные элементы)
https://github.com/inctnce/timetable-generator/blob/2bddf442e2433db153fa1974efdf5f8bccc2509d/src/helpers/sortTimetableDays/index.ts#L13
(Этот цикл вложен в цикл, распределяющий события по дням недели)
https://github.com/inctnce/timetable-generator/blob/2bddf442e2433db153fa1974efdf5f8bccc2509d/src/helpers/sortTimetableDays/index.ts#L17-L19
Собрав все уникальные интервалы, конвертируем в массив и сортируем
https://github.com/inctnce/timetable-generator/blob/2bddf442e2433db153fa1974efdf5f8bccc2509d/src/helpers/sortTimetableDays/index.ts#L36

Возможно в будущем придется сортировать равные элементы, поэтому, думаю, стоит поменять исходное условие
